# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ed4129f459a14bd356ac08b48bad837a63f7573c8afd80efff3da745469843f986500ad2e7fce36c7ef5e3594f499d934aa0e8e101cd2c0dd3e43359891f349

test:
  secret_key_base: 6eb6c3f801fc87e808752abc1ffb1d36873221ba54ffe1befe32ff282786560e38b8c91e59310a3e1a4e44e2f8d46ce04541e1684942edbaff1f84f32de6f146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
